# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hammer_builder}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Petr Chalupa"]
  s.date = %q{2011-05-17}
  s.description = %q{is a xhtml5 builder written in Ruby. It does not introduce anything special, you just
use Ruby to get your xhtml. HammerBuilder has been written with three objectives: Speed, Rich API, Extensibility}
  s.email = %q{email@pitr.ch}
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "README.md"
  ]
  s.files = [
    "lib/hammer_builder.rb",
    "lib/hammer_builder/dynamic_classes.rb"
  ]
  s.homepage = %q{https://github.com/ruby-hammer/hammer-builder}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.requirements = ["Ruby 1.9.2"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{fast ruby xhtml5 builder}
  s.test_files = ["spec/hammer_builder_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6"])
      s.add_development_dependency(%q<bluecloth>, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<yard>, ["~> 0.6"])
      s.add_dependency(%q<bluecloth>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<yard>, ["~> 0.6"])
    s.add_dependency(%q<bluecloth>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
  end
end

