# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hammer_builder"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Petr Chalupa"]
  s.date = "2013-05-17"
  s.description = "Fast extensible ruby html5 builder"
  s.email = "email@pitr.ch"
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "README.md"
  ]
  s.files = [
    "lib/hammer_builder.rb",
    "lib/hammer_builder/abstract.rb",
    "lib/hammer_builder/abstract/abstract_double_tag.rb",
    "lib/hammer_builder/abstract/abstract_single_tag.rb",
    "lib/hammer_builder/abstract/abstract_tag.rb",
    "lib/hammer_builder/data.rb",
    "lib/hammer_builder/data/html5.rb",
    "lib/hammer_builder/doc.rb",
    "lib/hammer_builder/dynamic_classes.rb",
    "lib/hammer_builder/formatted.rb",
    "lib/hammer_builder/helper.rb",
    "lib/hammer_builder/pool.rb",
    "lib/hammer_builder/rails.rb",
    "lib/hammer_builder/standard.rb",
    "lib/hammer_builder/strings_injector.rb"
  ]
  s.homepage = "https://github.com/ruby-hammer/hammer-builder"
  s.licenses = ["MIT"]
  s.post_install_message = "Gem Hammerwas renamed to htmless.\n\nThis version is here just for transition. It's identical to 0.3.1 and this gem won't\nbe developed further. Please see https://github.com/pitr-ch/htmless.\n"
  s.require_paths = ["lib"]
  s.requirements = ["Ruby 1.9"]
  s.rubygems_version = "1.8.23"
  s.summary = "Fast extensible ruby html5 builder"
  s.test_files = ["spec/hammer_builder_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.1"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bluecloth>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<ruby-prof>, [">= 0"])
      s.add_development_dependency(%q<perftools.rb>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<erubis>, [">= 0"])
      s.add_development_dependency(%q<tenjin>, [">= 0"])
      s.add_development_dependency(%q<erector>, [">= 0"])
      s.add_development_dependency(%q<markaby>, [">= 0"])
      s.add_development_dependency(%q<tagz>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.1"])
      s.add_runtime_dependency(%q<i18n>, ["~> 0.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6"])
      s.add_development_dependency(%q<bluecloth>, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.1"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bluecloth>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<ruby-prof>, [">= 0"])
      s.add_dependency(%q<perftools.rb>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<tenjin>, [">= 0"])
      s.add_dependency(%q<erector>, [">= 0"])
      s.add_dependency(%q<markaby>, [">= 0"])
      s.add_dependency(%q<tagz>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["~> 3.1"])
      s.add_dependency(%q<i18n>, ["~> 0.6"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<yard>, ["~> 0.6"])
      s.add_dependency(%q<bluecloth>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.1"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bluecloth>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<ruby-prof>, [">= 0"])
    s.add_dependency(%q<perftools.rb>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<tenjin>, [">= 0"])
    s.add_dependency(%q<erector>, [">= 0"])
    s.add_dependency(%q<markaby>, [">= 0"])
    s.add_dependency(%q<tagz>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<simplecov-rcov>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["~> 3.1"])
    s.add_dependency(%q<i18n>, ["~> 0.6"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<yard>, ["~> 0.6"])
    s.add_dependency(%q<bluecloth>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
  end
end

