# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name             = 'htmless'
  s.version          = '0.4'
  s.date             = '2013-05-12'
  s.summary          = 'Fast extensible html5 builder in pure Ruby'
  s.description      = 'Fast extensible html5 builder in pure Ruby'
  s.authors          = ['Petr Chalupa']
  s.email            = 'git@pitr.ch'
  s.homepage         = 'https://github.com/pitr-ch/htmless'
  s.extra_rdoc_files = %w(README.md README_FULL.md MIT-LICENSE)
  s.files            = Dir['lib/**/*.rb']
  s.require_paths    = %w(lib)
  s.license          = 'MIT'
  s.test_files       = Dir['spec/**/*.rb']


  #{}.each do |gem, version|
  #  s.add_runtime_dependency(gem, [version || '>= 0'])
  #end

  { 'rspec'          => nil,
    'yard'           => nil,
    'redcarpet'      => nil,
    'github-markup'  => nil,
    'nokogiri'       => nil,
    'erubis'         => nil,
    'tenjin'         => nil,
    'erector'        => nil,
    'markaby'        => nil,
    'tagz'           => nil,
    'simplecov'      => nil,
    'simplecov-rcov' => nil,
    'pry'            => nil,
    'multi_json'     => nil,
  }.each do |gem, version|
    s.add_development_dependency(gem, [version || '>= 0'])
  end
end
