module HammerBuilder
  EXTRA_ATTRIBUTES = {
      "a"          => ["href", "target", "ping", "rel", "media", "hreflang", "type"],
      "abbr"       => [],
      "address"    => [],
      "area"       => ["alt", "coords", "shape", "href", "target", "ping", "rel", "media", "hreflang", "type"],
      "article"    => [],
      "aside"      => [],
      "audio"      => ["src", "preload", "autoplay", "mediagroup", "loop", "controls"],
      "b"          => [],
      "base"       => ["href", "target"],
      "bdi"        => [],
      "bdo"        => [],
      "blockquote" => ["cite"],
      "body"       => ["onafterprint", "onbeforeprint", "onbeforeunload", "onblur", "onerror", "onfocus",
                       "onhashchange", "onload", "onmessage", "onoffline", "ononline", "onpagehide", "onpageshow",
                       "onpopstate", "onredo", "onresize", "onscroll", "onstorage", "onundo", "onunload"],
      "br"         => [],
      "button"     => ["autofocus", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate",
                       "formtarget", "name", "type", "value"],
      "canvas"     => ["width", "height"],
      "caption"    => [],
      "cite"       => [],
      "code"       => [],
      "col"        => ["span"],
      "colgroup"   => ["span"],
      "command"    => ["type", "label", "icon", "disabled", "checked", "radiogroup"],
      "datalist"   => ["option"],
      "dd"         => [],
      "del"        => ["cite", "datetime"],
      "details"    => ["open"],
      "dfn"        => [],
      "div"        => [],
      "dl"         => [],
      "dt"         => [],
      "em"         => [],
      "embed"      => ["src", "type", "width", "height"],
      "fieldset"   => ["disabled", "form", "name"],
      "figcaption" => [],
      "figure"     => [],
      "footer"     => [],
      "form"       => ["action", "autocomplete", "enctype", "method", "name", "novalidate", "target", 'accept_charset'],
      "h1"         => [],
      "h2"         => [],
      "h3"         => [],
      "h4"         => [],
      "h5"         => [],
      "h6"         => [],
      "head"       => [],
      "header"     => [],
      "hgroup"     => [],
      "hr"         => [],
      "html"       => ["manifest"],
      "i"          => [],
      "iframe"     => ["src", "srcdoc", "name", "sandbox", "seamless", "width", "height"],
      "img"        => ["alt", "src", "usemap", "ismap", "width", "height"],
      "input"      => ["accept", "alt", "autocomplete", "autofocus", "checked", "dirname", "disabled", "form",
                       "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "height", "list",
                       "max", "maxlength", "min", "multiple", "name", "pattern", "placeholder", "readonly", "required",
                       "size", "src", "step", "type", "value", "width"],
      "ins"        => ["cite", "datetime"],
      "kbd"        => [],
      "keygen"     => ["autofocus", "challenge", "disabled", "form", "keytype", "name"],
      "label"      => ["form", "for"],
      "legend"     => [],
      "li"         => ["value"],
      "link"       => ["href", "rel", "media", "hreflang", "type", "sizes"],
      "map"        => ["name"],
      "mark"       => [],
      "menu"       => ["type", "label"],
      "meta"       => ["name", "content", "charset", "http_equiv"],
      "meter"      => ["value", "min", "max", "low", "high", "optimum", "form"],
      "nav"        => [],
      "noscript"   => [],
      "object"     => ["data", "type", "name", "usemap", "form", "width", "height"],
      "ol"         => ["reversed", "start"],
      "optgroup"   => ["disabled", "label"],
      "option"     => ["disabled", "label", "selected", "value"],
      "output"     => ["for", "form", "name"],
      "p"          => [],
      "param"      => ["name", "value"],
      "pre"        => [],
      "progress"   => ["value", "max", "form"],
      "q"          => ["cite"],
      "rp"         => [],
      "rt"         => [],
      "ruby"       => [],
      "s"          => [],
      "samp"       => [],
      "script"     => ["src", "async", "defer", "type", "charset"],
      "section"    => [],
      "select"     => ["autofocus", "disabled", "form", "multiple", "name", "required", "size"],
      "small"      => [],
      "source"     => ["src", "type", "media"],
      "span"       => [],
      "strong"     => [],
      "style"      => ["media", "type", "scoped"],
      "sub"        => [],
      "summary"    => [],
      "sup"        => [],
      "table"      => ["border"],
      "tbody"      => [],
      "td"         => ["colspan", "rowspan", "headers"],
      "textarea"   => ["autofocus", "cols", "disabled", "form", "maxlength", "name", "placeholder", "readonly",
                       "required", "rows", "wrap"],
      "tfoot"      => [],
      "th"         => ["colspan", "rowspan", "headers", "scope"],
      "thead"      => [],
      "time"       => ["datetime", "pubdate"],
      "title"      => [],
      "tr"         => [],
      "track"      => ["default", "kind", "label", "src", "srclang"],
      "u"          => [],
      "ul"         => [],
      "var"        => [],
      "video"      => ["src", "poster", "preload", "autoplay", "mediagroup", "loop", "controls", "width", "height"],
      "wbr"        => []
  }

  GLOBAL_ATTRIBUTES = [
      'accesskey', 'class', 'contenteditable', 'contextmenu', 'dir', 'draggable', 'dropzone', 'hidden', 'id', 'lang',
      'spellcheck', 'style', 'tabindex', 'title', 'onabort', 'onblur', 'oncanplay', 'oncanplaythrough', 'onchange',
      'onclick', 'oncontextmenu', 'oncuechange', 'ondblclick', 'ondrag', 'ondragend', 'ondragenter', 'ondragleave',
      'ondragover', 'ondragstart', 'ondrop', 'ondurationchange', 'onemptied', 'onended', 'onerror', 'onfocus', 'oninput',
      'oninvalid', 'onkeydown', 'onkeypress', 'onkeyup', 'onload', 'onloadeddata', 'onloadedmetadata', 'onloadstart',
      'onmousedown', 'onmousemove', 'onmouseout', 'onmouseover', 'onmouseup', 'onmousewheel', 'onpause', 'onplay',
      'onplaying', 'onprogress', 'onratechange', 'onreadystatechange', 'onreset', 'onscroll', 'onseeked', 'onseeking',
      'onselect', 'onshow', 'onstalled', 'onsubmit', 'onsuspend', 'ontimeupdate', 'onvolumechange', 'onwaiting'
  ]

  DOUBLE_TAGS = [
      'a', 'abbr', 'article', 'aside', 'audio', 'address',
      'b', 'bdo', 'blockquote', 'body', 'button',
      'canvas', 'caption', 'cite', 'code', 'colgroup', 'command',
      'datalist', 'dd', 'del', 'details', 'dfn', 'div', 'dl', 'dt',
      'em',
      'fieldset', 'figure', 'footer', 'form',
      'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header', 'hgroup', 'html', 'i',
      'iframe', 'ins', 'keygen', 'kbd', 'label', 'legend', 'li',
      'map', 'mark', 'meter',
      'nav', 'noscript',
      'object', 'ol', 'optgroup', 'option',
      'p', 'pre', 'progress',
      'q', 'ruby', 'rt', 'rp', 's',
      'samp', 'script', 'section', 'select', 'small', 'source', 'span',
      'strong', 'style', 'sub', 'sup',
      'table', 'tbody', 'td', 'textarea', 'tfoot',
      'th', 'thead', 'time', 'title', 'tr',
      'u', 'ul',
      'var', 'video'
  ]

  EMPTY_TAGS = [
      'area', 'base', 'br', 'col', 'embed',
      'hr', 'img', 'input', 'link', 'meta', 'param'
  ]
end
